name: NPM Publish Alpha

on:
  push:
    branches-ignore:
      - main

jobs:
  npm-publish-alpha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Increment version with alpha tag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          SANITISED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-')
          TIMESTAMP=$(TZ='Europe/London' date +'%d-%m-%Y-%H%M%S')
          ALPHA_VERSION="${CURRENT_VERSION}-alpha.${SANITISED_BRANCH_NAME}.${TIMESTAMP}"
          npm version --no-git-tag-version $ALPHA_VERSION
          echo "Alpha version: $ALPHA_VERSION"

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc

      - name: Publish to NPM
        run: npm publish --tag alpha